---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node-app-deployment
  labels:
    app: test-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-node-app
  template:
    metadata:
      labels:
        app: test-node-app
    spec:
      containers:
      - name: test-node-app
        image: 461827005311.dkr.ecr.eu-central-1.amazonaws.com/test-node-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: test-node-app-service
spec:
  type: LoadBalancer
  selector:
    app: test-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
