version: 0.2
env:
  variables:
    PROJECT: "test-node-app"   #PROJECT NAME MUST ALLWAYS BE DEFINED (it also used as sonar project name)
    STAGE: "dev"
phases:
  install:
    commands:
      - echo 'install'
  build:
    commands:
      #insert here your build commands
      - echo 'build'
      - VERSION=$(bash scripts/versioning_aws)
      - echo ${DOCKERHUB_PASSWORD} | docker login --username ${DOCKERHUB_USERNAME} --password-stdin
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 461827005311.dkr.ecr.eu-central-1.amazonaws.com
      - docker build -t ${PROJECT}:latest -f Dockerfile.k8ts .
      - docker tag ${PROJECT}:latest 461827005311.dkr.ecr.eu-central-1.amazonaws.com/${PROJECT}:latest
      - docker tag ${PROJECT}:latest 461827005311.dkr.ecr.eu-central-1.amazonaws.com/${PROJECT}:${VERSION}
      - docker push 461827005311.dkr.ecr.eu-central-1.amazonaws.com/${PROJECT}
      - mkdir image
      - ls image
  post_build:
    commands:
      - ProjectFolder="${PROJECT}${Branch}"
      - sed -i "s/:FOLDER:/${ProjectFolder}/g" ./appspec.yml
      - sed -i "s/:FOLDER:/${ProjectFolder}/g" ./scripts/start_server
      - sed -i "s/:FOLDER:/${ProjectFolder}/g" ./scripts/stop_server
      - sed -i "s/:APPLICATION:/${ProjectFolder}/g" ./scripts/stop_server
      - sed -i "s/:APPLICATION:/${ProjectFolder}/g" ./scripts/start_server
      - sed -i "s/{{version}}/${VERSION}/g" ./docker-compose-dev.yml
      - cp appspec.yml image/
      - cp -r scripts image/
      - cp docker-compose*.yml image/
      - ls image
      - echo 'done'
artifacts:
  type: zip
  files:
    - "**/*"
  base-directory: image
