FROM node:14-alpine

WORKDIR /application
RUN chown node:node /application
USER node
ENV NODE_ENV=production \
    APPLICATION_NAME=helmnode2
COPY --chown=node:node . .
RUN npm install --unsafe-perm
ARG PORT=8080
ENV PORT=${PORT}

EXPOSE ${PORT}/tcp

CMD node index.js
